let downloadOptions = {video:[],audio:[],subtitle:[]};

// Nhận dữ liệu từ content script
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg.action === 'sendYoutubeCookiesToApp') {
    exportYoutubeCookiesToApp();
    return;
  }
  if (msg.action === 'setDownloadOptions') {
    downloadOptions = msg.data;
    return;
  }
  if (msg.action === 'getDownloadOptions') {
    sendResponse(downloadOptions);
    return true;
  }
  if (msg.action === 'downloadWithApp') {
    // Gửi HTTP về Flask app với đầy đủ thông tin format_id, target_ext, bitrate, lang...
    fetch('http://127.0.0.1:5678/add-link', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({
        url: msg.url,
        type: msg.type,
        format_id: msg.format_id,
        target_ext: msg.target_ext,
        bitrate: msg.bitrate,
        lang: msg.lang
      })
    });
    return;
  }
});

function exportYoutubeCookiesToApp() {
  chrome.cookies.getAll({domain: ".youtube.com"}, function(cookies) {
    let lines = [
      '# Netscape HTTP Cookie File',
      '# This file is generated by IDM Pikachu extension',
      '# http://curl.haxx.se/rfc/cookie_spec.html',
      '# This is a generated file! Do not edit.'
    ];
    lines = lines.concat(cookies.map(c => [
      c.domain,
      c.hostOnly ? 'FALSE' : 'TRUE',
      c.path,
      c.secure ? 'TRUE' : 'FALSE',
      c.expirationDate ? Math.floor(c.expirationDate) : 0,
      c.name,
      c.value
    ].join('\t')));
    lines = lines.join('\n');
    fetch('http://127.0.0.1:5678/upload-cookies', {
      method: 'POST',
      headers: {'Content-Type': 'text/plain'},
      body: lines
    });
  });
}

// Gửi cookies khi extension khởi động hoặc cài đặt/reload nữa
// chrome.runtime.onStartup.addListener(() => {
//   exportYoutubeCookiesToApp();
// });
// chrome.runtime.onInstalled.addListener(() => {
//   exportYoutubeCookiesToApp();
//   ...
// });
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "idm-pikachu-download",
    title: "Tải bằng IDM Pikachu",
    contexts: ["link", "video", "audio"]
  });
  chrome.contextMenus.create({
    id: "idm-pikachu-send-cookies",
    title: "Gửi cookies YouTube cho IDM Pikachu",
    contexts: ["page"]
  });
});

chrome.contextMenus.onClicked.addListener((info, tab) => {
  if (info.menuItemId === "idm-pikachu-send-cookies") {
    exportYoutubeCookiesToApp();
    return;
  }
  let url = info.linkUrl || info.srcUrl || (tab && tab.url);
  if (!url) return;
  // Nếu là blob, thay bằng link YouTube gốc
  if (url.startsWith('blob:') && tab && tab.url && tab.url.includes('youtube.com')) {
    url = tab.url;
  }
  // Nếu là link YouTube, Facebook, TikTok... thì mở overlay chọn chất lượng (giữ nguyên)
  if (
    url.includes('youtube.com') || url.includes('youtu.be') ||
    url.includes('facebook.com') || url.includes('fb.watch') ||
    url.includes('tiktok.com')
  ) {
    chrome.tabs.sendMessage(tab.id, {action: 'showOverlay', url: url});
    return;
  }
  // Nếu là link thường (file, ảnh, v.v), gửi thẳng về app
  fetch('http://127.0.0.1:5678/add-link', {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({
      url: url,
      type: 'auto'
    })
  }).then(() => {
    chrome.notifications.create({
      type: "basic",
      iconUrl: "icon128.png",
      title: "IDM Pikachu",
      message: "Đã gửi link về app!"
    });
  });
});
